version: "2.1"
services:
  db:
    image: mysql:latest
    volumes:
      - ./database:/docker-entrypoint-initdb.d:rw
    environment:
      - MYSQL_ROOT_PASSWORD=p4$$W0rd
      - MYSQL_DATABASE=epidemics
      - MYSQL_USER=epidemics
      - MYSQL_PASSWORD=epidemics
    ports:
      - 3306:3306
    healthcheck:
      test: "exit 0"
  fhir:
    image: djohnson325/hapi-fhir-jpaserver:stu3-ext-6-patient
    ports: 
      - 8081:8080
  web:
    image: epidemics/epidemics-web
    volumes:
      - ./src/main/webapp:/usr/local/tomcat/webapps/webapp:rw
    build: .
    depends_on:
      db:
        condition: service_healthy
      fhir:
        condition: service_started
    ports:
      - 8080:8080
    environment:
      - DATABASE_HOST=db
      - DATABASE_USER=epidemics
      - DATABASE_PASSWORD=epidemics
      - DATABASE_NAME=epidemics
      - DATABASE_PORT=3306