spring:
  datasource:
    url: jdbc:mysql://localhost:3306/epidemics
    username: root
    password: p4SSW0rd
    platform: mysql
    initialize: false

---
spring:
  profiles: container
  datasource:
    url: jdbc:mysql://${DATABASE_HOST}:${DATABASE_PORT}/${DATABASE_NAME}
    username: ${DATABASE_USER}
    password: ${DATABASE_PASSWORD}
    initialize: true