# MySQL Setup
SET default_storage_engine=InnoDB;

USE epidemics;

DROP TABLE IF EXISTS person;

CREATE TABLE person (
`id` INT NOT NULL AUTO_INCREMENT PRIMARY KEY,
`username` VARCHAR(25) NOT NULL,
`password` VARCHAR(50),
`active` BIT(1),
`personType` ENUM('PATIENT', 'DOCTOR') NOT NULL,
`firstName` VARCHAR(50) NOT NULL,
`middleName` VARCHAR(50) NULL,
`lastName` VARCHAR(50) NOT NULL,
`contactPhone` VARCHAR(50) NULL,
`contactEmail` VARCHAR(50) NULL,
`contactFax` VARCHAR(50) NULL,
`addressLine1` VARCHAR(100) NULL,
`addressLine2` VARCHAR(100) NULL,
`city` VARCHAR(50) NULL,
`state` VARCHAR(50) NULL,
`zip` VARCHAR(10) NULL
)ENGINE=InnoDB;

DROP TABLE IF EXISTS ageGroup;

CREATE TABLE ageGroup (
`id` INT NOT NULL AUTO_INCREMENT PRIMARY KEY,
`minAge` INT NOT NULL,
`maxAge` INT NOT NULL,
`description` VARCHAR(100) NOT NULL
)ENGINE=InnoDB;

DROP TABLE IF EXISTS question;

CREATE TABLE question (
`id` INT NOT NULL AUTO_INCREMENT PRIMARY KEY,
`ageGroupId` INT NOT NULL,
`questionNumber` INT NOT NULL,
`questionText` VARCHAR(2000) NOT NULL,
`domainOfControl` ENUM('IMPAIRMENT', 'RISK') NOT NULL,
FOREIGN KEY(ageGroupId)
  REFERENCES ageGroup(id)
  ON DELETE CASCADE
)ENGINE=InnoDB;

DROP TABLE IF EXISTS answerChoice;

CREATE TABLE answerChoice (
`id` INT NOT NULL AUTO_INCREMENT PRIMARY KEY,
`questionId` INT NOT NULL,
`answerText` VARCHAR(1000) NOT NULL,
FOREIGN KEY(questionId)
  REFERENCES question(id)
  ON DELETE CASCADE
)ENGINE=InnoDB;

DROP TABLE IF EXISTS visit;
CREATE TABLE visit (
`id` INT NOT NULL AUTO_INCREMENT PRIMARY KEY,
`patientId` INT NOT NULL REFERENCES person(id),
`authorId` INT NOT NULL REFERENCES person(id),
`visitDate` DATETIME NOT NULL,
FOREIGN KEY(patientId)
  REFERENCES person(id)
  ON DELETE CASCADE,
FOREIGN KEY(authorId)
  REFERENCES person(id)
  ON DELETE CASCADE
)ENGINE=InnoDB;

DROP TABLE IF EXISTS response;

CREATE TABLE response (
`id` INT NOT NULL AUTO_INCREMENT PRIMARY KEY,
`visitId` INT NOT NULL REFERENCES visit(id),
`questionId` INT NOT NULL REFERENCES question(id),
`answerId` INT NOT NULL REFERENCES answerChoice(id),
FOREIGN KEY(visitId)
  REFERENCES visit(id)
  ON DELETE CASCADE,
FOREIGN KEY(questionId)
  REFERENCES question(id)
  ON DELETE CASCADE,
FOREIGN KEY(answerId)
  REFERENCES answerChoice(id)
  ON DELETE CASCADE
)ENGINE=InnoDB;
